version: "1.0"
info:
  model: int-scaffold
packages:
- name: Serengeti_GH_VIrginiaProject
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
